eka = input('kerro kokonais luku')
toka = input('kerro toinen')
kolmas = input('kerro vielä kolmas')
eka = float(eka)
toka = float(toka)
kolmas = float(kolmas)
summa = (eka + toka + kolmas)
tulo = (eka * toka * kolmas)
keski = (tulo / 3)
print (f'summa on {summa}')
print(f'tulo on {tulo}')
print (f'keskiarvo on {keski}')