levis = input('anna leiviskät')
naulat = input('anna naulat')
luodit = input('anna luodit')
levis = float(levis)
naulat = float(naulat)
luodit = float(luodit)
le = float(8500)
na = float(425)
lu = float(13.3)
eka = (levis * le)
toka = (naulat * na)
kolmas = (luodit * lu)
grammat = (eka + toka + kolmas)
kilot = grammat / 1000
kilot = int(kilot)
gram = grammat - (kilot * 1000)
print(f'Kilogrammat: {kilot} kg')
print(f'Grammat: {gram:.2f} g')